import {
    FileText,
    FileCheck,
    Upload,
    Search,
    Eye,
    GitBranch,
    Brain,
    Activity,
    Layers,
    Database,
    CheckCircle,
    Sparkles,
    BarChart3,
    FileJson,
    FileSpreadsheet,
    Network,
} from "lucide-react";

export const inputNodes = [
    {
        id: "invoice",
        label: "Invoice",
        emoji: "🧾",
        icon: FileText,
        description: "PDF & scanned invoices",
        type: "input",
        position: { x: 5, y: 18 },
        color: "blue",
    },
    {
        id: "contract",
        label: "Contract",
        emoji: "📄",
        icon: FileCheck,
        description: "Legal documents",
        type: "input",
        position: { x: 5, y: 38 },
        color: "blue",
    },
    {
        id: "forms",
        label: "Forms",
        emoji: "📋",
        icon: Upload,
        description: "Structured forms",
        type: "input",
        position: { x: 5, y: 58 },
        color: "blue",
    },
    {
        id: "research",
        label: "Research",
        emoji: "🔍",
        icon: Search,
        description: "Research papers",
        type: "input",
        position: { x: 5, y: 78 },
        color: "blue",
    },
];

export const processingNodes = [
    {
        id: "ocr",
        label: "OCR",
        icon: Eye,
        description: "Text extraction",
        type: "process",
        position: { x: 25, y: 22 },
        risk: "Manual typing errors",
        color: "blue",
    },
    {
        id: "parser",
        label: "Parser",
        icon: GitBranch,
        description: "Structure detection",
        type: "process",
        position: { x: 25, y: 52 },
        risk: "Template breaks",
        color: "blue",
    },
    {
        id: "nlp",
        label: "NLP",
        icon: Activity,
        description: "Language understanding",
        type: "process",
        position: { x: 25, y: 82 },
        risk: "Context loss",
        color: "blue",
    },
    {
        id: "ai-core",
        label: "AI Core",
        icon: Brain,
        description: "Deep learning engine",
        type: "core",
        position: { x: 50, y: 50 },
        size: 110,
        color: "core",
    },
    {
        id: "classifier",
        label: "Classifier",
        icon: Layers,
        description: "Type detection",
        type: "process",
        position: { x: 42, y: 20 },
        color: "blue",
    },
    {
        id: "extractor",
        label: "Extractor",
        icon: Database,
        description: "Field extraction",
        type: "process",
        position: { x: 58, y: 20 },
        color: "blue",
    },
    {
        id: "validator",
        label: "Validator",
        icon: CheckCircle,
        description: "Data validation",
        type: "process",
        position: { x: 42, y: 80 },
        color: "blue",
    },
    {
        id: "enricher",
        label: "Enricher",
        icon: Sparkles,
        description: "Data enrichment",
        type: "process",
        position: { x: 58, y: 80 },
        color: "blue",
    },
    {
        id: "analyzer",
        label: "Analyzer",
        icon: BarChart3,
        description: "Pattern analysis",
        type: "process",
        position: { x: 75, y: 50 },
        risk: "Missed patterns",
        color: "blue",
    },
];

export const outputNodes = [
    {
        id: "json",
        label: "JSON",
        icon: FileJson,
        description: "Structured data",
        type: "output",
        position: { x: 95, y: 18 },
        color: "green",
    },
    {
        id: "excel",
        label: "Excel",
        icon: FileSpreadsheet,
        description: "Spreadsheets",
        type: "output",
        position: { x: 95, y: 38 },
        color: "green",
    },
    {
        id: "database",
        label: "Database",
        icon: Database,
        description: "Direct DB insert",
        type: "output",
        position: { x: 95, y: 58 },
        color: "green",
    },
    {
        id: "api",
        label: "API",
        icon: Network,
        description: "REST endpoints",
        type: "output",
        position: { x: 95, y: 78 },
        color: "green",
    },
];

export const allNodes = [...inputNodes, ...processingNodes, ...outputNodes];

export const connections = [
    // Inputs to first layer processing
    { from: "invoice", to: "ocr" },
    { from: "invoice", to: "parser" },
    { from: "contract", to: "ocr" },
    { from: "contract", to: "parser" },
    { from: "contract", to: "nlp" },
    { from: "forms", to: "parser" },
    { from: "forms", to: "nlp" },
    { from: "research", to: "nlp" },
    { from: "research", to: "ocr" },

    // First layer to classifier/extractor
    { from: "ocr", to: "classifier" },
    { from: "ocr", to: "extractor" },
    { from: "parser", to: "classifier" },
    { from: "parser", to: "ai-core" },
    { from: "nlp", to: "ai-core" },
    { from: "nlp", to: "validator" },

    // AI Core connections (hub)
    { from: "classifier", to: "ai-core" },
    { from: "extractor", to: "ai-core" },
    { from: "ai-core", to: "validator" },
    { from: "ai-core", to: "enricher" },
    { from: "ai-core", to: "analyzer" },

    // Cross connections in processing
    { from: "classifier", to: "extractor" },
    { from: "extractor", to: "enricher" },
    { from: "validator", to: "enricher" },
    { from: "enricher", to: "analyzer" },
    { from: "validator", to: "analyzer" },

    // Processing to outputs
    { from: "analyzer", to: "json" },
    { from: "analyzer", to: "excel" },
    { from: "analyzer", to: "database" },
    { from: "analyzer", to: "api" },
    { from: "enricher", to: "json" },
    { from: "enricher", to: "database" },
    { from: "validator", to: "excel" },
    { from: "validator", to: "api" },
];